### PR TITLE
EPG search timer

### PR DESCRIPTION
**Pull request by FernetMenta**

### CODE REVIEW

**Comment by ksooo** [comment]
Nice.

**Comment by FernetMenta** [comment]
@ksooo I would have 2 questions regarding this

1) When I start Kodi with only a single search timer, I get notification that next active recording is i.e. "Tageschau".
Somehow irritating because the searchtimer itself does not record

2) What's timer rules? This dialog is always empty for me.

**Comment by ksooo** [comment]
Timer rules describe the conditions for recording something. So, a search timer is a timer rule.

Please set PVR_TIMER_TYPE_IS_REPEATING in addition to the attributes you already set to indicate that a timer type is a rule. => https://github.com/kodi-pvr/pvr.vdr.vnsi/pull/80/files#diff-7ff58f2823de0d287f817f6017821d0fR720 and here https://github.com/kodi-pvr/pvr.vdr.vnsi/pull/80/files#diff-7ff58f2823de0d287f817f6017821d0fR733

Then, "Timer rules" shall get filled with all your search timers and "Timers" will contain the actual timers scheduled by the search timer. The "next" recording" widget will no longer show any search timers.

**Comment by FernetMenta** [comment]
Thanks, that works. Now I have the next question.

1) When I disable a search timer, I get a kai toast saying "recording aborted". Makes not much sense to me. What is the intent here?

2) The context menu of the search timer always show "deactivate" regardless of the actual state of the timer. Known bug?

**Comment by ksooo** [comment]
> When I disable a search timer, I get a kai toast saying "recording aborted". 

> The context menu of the search timer always show "deactivate"

 Seems that you set the timer state to PVR_TIMER_STATE_ABORTED or PVR_TIMER_STATE_CANCELLED on disable. This causes the kai toast. You should set the timer state to PVR_TIMER_STATE_DISABLE.

**Comment by FernetMenta** [comment]
Thanks again

**Pull request merged**
