### PR TITLE
update p8platform api

### PR DESCRIPTION
**Pull request by frostworx**
should fix building against more recent platform api
and therefore should fix buildproblems like:
https://forums.gentoo.org/viewtopic-p-7851740.html#7851740

### CODE REVIEW

**Comment by wsnipex** [comment]
this need updating in https://github.com/xbmc/kodi-platform first

**Comment by frostworx** [comment]
heh, indeed. thx for the quick reply.

**Comment by FernetMenta** [comment]
I think we should update after the branch to Jarvis has been created

**Comment by wsnipex** [comment]
yes indeed, this shouldn't go into jarvis

**Comment by frostworx** [comment]
makes sense. not everyone is using bleeding edge.
might come in handy for one or another if there was a (official) branch though(?)

**Comment by FernetMenta** [comment]
@frostworx we are short final for Jarvis and will branch soon

**Comment by frostworx** [comment]
sounds good. thanks for the quick reply, FernetMenta!

**Comment by MartijnKaijser** [comment]
Obsolete by now

**Pull request closed without merging**
