### PR TITLE
Update to use newest vdr plugin for channel scan

### PR DESCRIPTION
**Pull request by AlwinEsch**
The following change fix and update the usage of wirbelscan plugin on VDR.
Is tested here on DVB-C.

### CODE REVIEW

**Comment by AlwinEsch** [comment]
This part seems to be OK. On next KODI Version must be a Render Thread call introduced to remove this hack way with dummy "renderaddon", also must be on next a another way introduced to get the country instead of GetDVDMenuLanguage.

**Comment by FernetMenta** [comment]
looks good

**Comment by MartijnKaijser** [comment]
@FernetMenta small nudge? Maybe this was forgotten?

**Comment by FernetMenta** [comment]
@AlwinEsch this depends on some other PR in mainline, right?

**Comment by AlwinEsch** [comment]
Yes, I'm do as next steps a split of my pull request on kodi. There is a reported fault and want only have the related code of them there. After this is done, fault fixed and added to kodi can this one in.

**Pull request closed without merging**
