### PR TITLE
Updated to GUI API v5.10.0

### PR DESCRIPTION
**Pull request by hudokkow**
Addon side of https://github.com/xbmc/xbmc/pull/8494

### CODE REVIEW

**Comment by FernetMenta** [comment]
why?

**Comment by FernetMenta** [comment]
when do you intend to branch pvr addons for Jarvis?

**Comment by ksooo** [comment]
On first k****- or Jarvis-only pvr add-on change - means as late as possible.

**Comment by MartijnKaijser** [comment]
atm both master and Jarvis still use the same branch for the addons. This save a lot of time because we don't need to handle backporting and so on. On the first change that will affect binary add-ons we'll have to branch all of them.

**Pull request merged**
