### PR TITLE
Fix path to CMakeLists.txt

### PR DESCRIPTION
**Pull request by Markieta**

### CODE REVIEW

**Comment by FernetMenta** [comment]
that is wrong for Krypton. it has changed for v18

**Comment by Markieta** [comment]
When will the change be merged into master? The instructions are misleading users who are unfamiliar with the repository and just need to build the plugins.

**Comment by FernetMenta** [comment]
this repo has no master. master has moved to https://github.com/FernetMenta/pvr.vdr.vnsi

**Comment by Markieta** [comment]
The xbmc repo. The path: `xbmc/project/cmake/addons` does not exist in https://github.com/xbmc/xbmc/tree/master/project

This is the default branch being cloned according to the readme.

**Comment by FernetMenta** [comment]
https://github.com/kodi-pvr/pvr.vdr.vnsi is for <= v17

vnsi repo for >= v18 has moved to
https://github.com/FernetMenta/pvr.vdr.vnsi

see:
https://github.com/xbmc/repo-binary-addons/blob/master/pvr.vdr.vnsi/pvr.vdr.vnsi.txt

That means that you submitted the change to the wrong repo. Please submit it to
https://github.com/FernetMenta/pvr.vdr.vnsi

**Comment by Markieta** [comment]
But my change works for <= v17. In that case this should be the right repo.

**Comment by FernetMenta** [comment]
No, they do not. v17 path is project/cmake/addons:
https://github.com/xbmc/xbmc/tree/Krypton/project/cmake/addons

**Comment by Markieta** [comment]
I understand now, I was thinking Krypton was v18 not v17. Sorry for the confusion.

**Comment by FernetMenta** [comment]
np :), you are welcome

**Pull request closed without merging**
