### PR TITLE
adapt to pvr api change in stream props

### PR DESCRIPTION
**Pull request by FernetMenta**
see title

@Jalle19 /cc

### CODE REVIEW

**Comment by Jalle19** [comment]
Made an issue about it so I don't forget it. Haven't had that much time to work on Kodi lately so I don't know when I will get around to it though.

**Comment by FernetMenta** [comment]
> Made an issue about it so I don't forget it

you'll notice when it breaks anyway :)

**Comment by ksooo** [comment]
> Made an issue about it so I don't forget it. Haven't had that much time to work on Kodi lately so I don't know when I will get around to it though.

@Jalle19 @FernetMenta I will try to make the related pvr.hts changes. Not my home playground, but I'd like to learn... :-)

**Comment by FernetMenta** [comment]
@ksooo should be pretty straightforward. The code in hts should be identical to the one in vnsi (at least it was used to be)
Let me know if I can help.

**Comment by ksooo** [comment]
> The code in hts should be identical to the one in vnsi (at least it was used to be)

 yep. did a quick check before I volunteered. ;-)

**Comment by ksooo** [comment]
@FernetMenta In a moment, I will come up with a PR for vdr.vnsi which does the the actual api and addon version bump and the other 5.1.0 stubbing.

**Comment by ksooo** [comment]
@FernetMenta #61 Feel free to merge.

**Pull request merged**
